package dev.ividi.militarycalisthenics.ui

import androidx.compose.runtime.Composable
import androidx.compose.runtime.CompositionLocalProvider
import androidx.compose.runtime.compositionLocalOf

enum class Lang { PT, EN }

private val strings: Map<String, Pair<String, String>> = mapOf(
    "app_title" to ("Calistenia Militar" to "Military Calisthenics"),
    "onboarding_title" to ("Cria o teu perfil" to "Build your profile"),
    "onboarding_subtitle" to ("Diz-nos quem és. Nós tratamos do plano." to "Tell us about yourself. We'll build the plan."),
    "weight" to ("Peso (kg)" to "Weight (kg)"),
    "height" to ("Altura (cm)" to "Height (cm)"),
    "age" to ("Idade" to "Age"),
    "sex" to ("Sexo" to "Sex"),
    "sex_male" to ("Masculino" to "Male"),
    "sex_female" to ("Feminino" to "Female"),
    "sex_unspecified" to ("Prefiro não dizer" to "Prefer not to say"),
    "level" to ("Nível" to "Level"),
    "level_beginner" to ("Iniciante" to "Beginner"),
    "level_intermediate" to ("Intermédio" to "Intermediate"),
    "level_advanced" to ("Avançado" to "Advanced"),
    "goal" to ("Objetivo" to "Goal"),
    "goal_fat_loss" to ("Perda de gordura" to "Fat loss"),
    "goal_strength_mass" to ("Força e massa" to "Strength & mass"),
    "goal_military_endurance" to ("Resistência militar" to "Military endurance"),
    "goal_mobility" to ("Mobilidade geral" to "General mobility"),
    "days_per_week" to ("Dias por semana" to "Days per week"),
    "equipment" to ("Equipamento" to "Equipment"),
    "equipment_bodyweight" to ("Só peso do corpo" to "Bodyweight only"),
    "equipment_bar" to ("Barra de tração" to "Pull-up bar"),
    "equipment_parallettes" to ("Paralelas" to "Parallettes"),
    "generate_plan" to ("Gerar plano" to "Generate plan"),
    "your_plan" to ("O teu plano" to "Your plan"),
    "week" to ("Semana" to "Week"),
    "day" to ("Dia" to "Day"),
    "warm_up" to ("Aquecimento" to "Warm-up"),
    "strength" to ("Força" to "Strength"),
    "circuit" to ("Circuito" to "Circuit"),
    "core" to ("Core" to "Core"),
    "cool_down" to ("Arrefecimento" to "Cool-down"),
    "sets" to ("séries" to "sets"),
    "reps" to ("reps" to "reps"),
    "seconds" to ("seg" to "sec"),
    "mark_done" to ("Marcar como feito" to "Mark as done"),
    "completed" to ("Concluído" to "Completed"),
    "edit_profile" to ("Editar perfil" to "Edit profile"),
    "profile_section" to ("Perfil" to "Profile"),
    "regenerate_plan" to ("Gerar novo plano" to "Regenerate plan"),
    "regenerate_plan_subtitle" to ("Cria um plano novo para o teu perfil atual, ou muda os teus dados." to "Get a fresh plan for your current profile, or change your details."),
    "plan_regenerated" to ("Plano gerado de novo." to "Plan regenerated."),
    "delete" to ("Eliminar" to "Delete"),
    "about" to ("Sobre" to "About"),
    "developed_by" to ("Desenvolvido por David Arsénio Martins" to "Developed by David Arsénio Martins"),
    "website" to ("Website" to "Website"),
    "github" to ("GitHub" to "GitHub"),
    "settings" to ("Definições" to "Settings"),
    "language" to ("Idioma" to "Language"),
    "theme" to ("Tema" to "Theme"),
    "theme_dark" to ("Escuro" to "Dark"),
    "theme_light" to ("Claro" to "Light"),
    "theme_system" to ("Sistema" to "System"),
    "error_range" to ("Valor fora do intervalo esperado" to "Value out of expected range"),
    "plan_complete_title" to ("Plano concluído!" to "Plan complete!"),
    "plan_complete_subtitle" to ("Terminaste todas as semanas do teu plano atual. O que queres fazer a seguir?" to "You've finished every week of your current plan. What do you want to do next?"),
    "plan_complete_repeat" to ("Repetir este nível" to "Repeat this level"),
    "plan_complete_repeat_subtitle" to ("Recomeça o mesmo plano do zero" to "Restart the same plan from scratch"),
    "plan_complete_level_up" to ("Subir para" to "Level up to"),
    "plan_complete_level_up_subtitle" to ("Novo plano, mais exigente" to "New plan, more demanding"),
    "plan_complete_max_level" to ("Já estás no nível máximo. Podes repetir o plano para continuar a treinar." to "You're already at the top level. You can repeat the plan to keep training."),
    "plan_complete_dismiss" to ("Continuar a ver o plano" to "Keep viewing the plan"),
    "close" to ("Fechar" to "Close"),
    "back" to ("Voltar" to "Back"),
    "cue_push_up" to ("Mantém o corpo alinhado, desce até quase tocar no chão." to "Keep your body straight, lower until you nearly touch the floor."),
    "cue_squat" to ("Pés à largura dos ombros, desce como se fosses sentar numa cadeira." to "Feet shoulder-width apart, lower like sitting into a chair."),
    "cue_pull_up" to ("Pega firme na barra, puxa até o queixo passar a barra." to "Grip the bar firmly, pull until your chin clears the bar."),
    "cue_row" to ("Corpo reto, puxa o peito em direção à barra." to "Keep your body straight, pull your chest toward the bar."),
    "cue_dip" to ("Cotovelos para trás, desce até cerca de 90 graus." to "Elbows back, lower until your arms reach about 90 degrees."),
    "cue_lunge" to ("Dá um passo em frente, desce o joelho de trás quase ao chão." to "Step forward, lower your back knee almost to the floor."),
    "cue_burpee" to ("Agacha, estica para prancha, salta com as mãos acima da cabeça." to "Squat down, kick back to a plank, jump with hands overhead."),
    "cue_mountain_climber" to ("Em prancha, traz os joelhos ao peito alternadamente e depressa." to "From a plank, drive your knees to your chest quickly, alternating sides."),
    "cue_sprint" to ("De pé, corre no lugar levantando bem os joelhos." to "Standing tall, drive your knees up quickly as if sprinting on the spot."),
    "progress" to ("Progresso" to "Progress"),
    "log_weight" to ("Registar peso" to "Log weight"),
    "weight_history" to ("Histórico de peso" to "Weight history"),
    "log_weight_subtitle" to ("O teu plano ajusta-se automaticamente ao novo peso." to "Your plan recalibrates automatically to the new weight."),
    "save" to ("Guardar" to "Save"),
    "no_weight_history" to ("Ainda sem registos de peso." to "No weight entries yet."),
    "plan_recalibrated" to ("Plano recalibrado com o novo peso." to "Plan recalibrated with your new weight."),
    "cue_plank" to ("Corpo reto da cabeça aos calcanhares, core contraído." to "Keep a straight line from head to heels, core braced."),
    "cue_leg_raise" to ("Deitado, sobe as pernas esticadas sem levantar as costas." to "Lying down, raise your straight legs without lifting your lower back."),
    "cue_twist" to ("Sentado, gira o tronco de um lado para o outro." to "Seated, rotate your torso from side to side."),
    "cue_jumping_jack" to ("Salta abrindo pernas e braços ao mesmo tempo." to "Jump while spreading your arms and legs at the same time."),
    "cue_stretch" to ("Movimento suave e controlado, sem forçar a articulação." to "Move slowly and with control, never forcing the joint."),
    "cue_arm_circles" to ("De pé, faz círculos largos com os braços, para a frente e para trás." to "Standing tall, sweep your arms in wide circles, forward and backward."),
    "cue_hip_openers" to ("De pé, levanta o joelho e roda a anca para fora, num movimento controlado." to "Standing tall, lift your knee and rotate your hip outward with control."),
    "cue_worlds_greatest_stretch" to ("Em avanço, roda o tronco e estica um braço para o teto." to "From a lunge, rotate your torso and reach one arm toward the ceiling."),
    "cue_cat_cow" to ("De quatro apoios, arqueia as costas e depois arredonda a coluna." to "On hands and knees, arch your back, then round your spine."),
    "cue_good_mornings" to ("De pé, dobra a anca com as costas direitas, pernas quase esticadas." to "Standing tall, hinge at the hips with a flat back, legs almost straight."),
    "cue_deep_breathing" to ("Inspira profundamente enchendo o peito, expira devagar." to "Breathe in deeply, filling your chest, then exhale slowly."),
    "cue_hamstring_stretch" to ("Perna estendida à frente, inclina o tronco em direção ao pé." to "Extend one leg forward, hinge your torso toward your foot."),
    "cue_shoulder_stretch" to ("Puxa um braço esticado por cima do peito com a outra mão." to "Pull one straight arm across your chest with the other hand."),
    "share_plan" to ("Partilhar" to "Share"),
    "reminders" to ("Lembretes de treino" to "Workout reminders"),
    "reminders_subtitle" to ("Recebe uma notificação diária à hora escolhida." to "Get a daily notification at the chosen time."),
    "reminder_time" to ("Hora do lembrete" to "Reminder time"),
    "reminder_notification_title" to ("Hora de treinar" to "Time to train"),
    "reminder_notification_body" to ("O teu plano de calistenia militar está à tua espera." to "Your military calisthenics plan is waiting for you."),
    "notifications_denied" to ("Permite notificações nas definições do sistema para receber lembretes." to "Allow notifications in system settings to receive reminders."),
    "pending" to ("Pendente" to "Pending"),

    // Day/block focus titles (PlanEngine.dayTitle) — English text is the stable key.
    "Full Body Burn" to ("Queima Corpo Inteiro" to "Full Body Burn"),
    "Metabolic Circuit" to ("Circuito Metabólico" to "Metabolic Circuit"),
    "Core & Cardio" to ("Core & Cardio" to "Core & Cardio"),
    "Total Conditioning" to ("Condicionamento Total" to "Total Conditioning"),
    "Endurance Push" to ("Impulso de Resistência" to "Endurance Push"),
    "Active Recovery" to ("Recuperação Ativa" to "Active Recovery"),
    "Push Strength" to ("Força de Empurrar" to "Push Strength"),
    "Pull Strength" to ("Força de Puxar" to "Pull Strength"),
    "Legs & Core" to ("Pernas & Core" to "Legs & Core"),
    "Upper Power" to ("Potência Superior" to "Upper Power"),
    "Full Body Strength" to ("Força Corpo Inteiro" to "Full Body Strength"),
    "Grip & Core" to ("Pega & Core" to "Grip & Core"),
    "Selection Prep" to ("Preparação para Seleção" to "Selection Prep"),
    "Ruck & Core" to ("Marcha com Carga & Core" to "Ruck & Core"),
    "Speed Endurance" to ("Resistência de Velocidade" to "Speed Endurance"),
    "Combat Circuit" to ("Circuito de Combate" to "Combat Circuit"),
    "Max Reps Test" to ("Teste de Repetições Máximas" to "Max Reps Test"),
    "Recovery Mobility" to ("Mobilidade de Recuperação" to "Recovery Mobility"),
    "Mobility Flow" to ("Fluxo de Mobilidade" to "Mobility Flow"),
    "Control & Balance" to ("Controlo & Equilíbrio" to "Control & Balance"),
    "Light Strength" to ("Força Leve" to "Light Strength"),
    "Joint Health" to ("Saúde Articular" to "Joint Health"),
    "Full Body Flow" to ("Fluxo Corpo Inteiro" to "Full Body Flow"),
    "Active Stretch" to ("Alongamento Ativo" to "Active Stretch"),

    // Exercise names (PlanEngine blocks) — English text is the stable key.
    "Jumping Jacks" to ("Polichinelos" to "Jumping Jacks"),
    "Arm Circles" to ("Círculos de Braços" to "Arm Circles"),
    "Bodyweight Squats" to ("Agachamentos com Peso do Corpo" to "Bodyweight Squats"),
    "Hip Openers" to ("Abertura de Anca" to "Hip Openers"),
    "Push-ups" to ("Flexões" to "Push-ups"),
    "Pull-ups" to ("Dominadas" to "Pull-ups"),
    "Inverted Rows / Table Rows" to ("Remo Invertido / Remo de Mesa" to "Inverted Rows / Table Rows"),
    "Parallel Bar Dips" to ("Fundos em Paralelas" to "Parallel Bar Dips"),
    "Bench Dips" to ("Fundos no Banco" to "Bench Dips"),
    "Lunges" to ("Avanços" to "Lunges"),
    "Burpees" to ("Burpees" to "Burpees"),
    "Mountain Climbers" to ("Escaladores" to "Mountain Climbers"),
    "Sprint Intervals" to ("Sprints Intervalados" to "Sprint Intervals"),
    "High Knees" to ("Joelhos Altos" to "High Knees"),
    "Jump Squats" to ("Agachamentos com Salto" to "Jump Squats"),
    "Pike Push-ups" to ("Flexões em Pique" to "Pike Push-ups"),
    "Explosive Push-ups" to ("Flexões Explosivas" to "Explosive Push-ups"),
    "World's Greatest Stretch" to ("O Maior Alongamento" to "World's Greatest Stretch"),
    "Cat-Cow" to ("Gato-Vaca" to "Cat-Cow"),
    "Bodyweight Good Mornings" to ("Good Mornings com Peso do Corpo" to "Bodyweight Good Mornings"),
    "Plank" to ("Prancha" to "Plank"),
    "Leg Raises" to ("Elevação de Pernas" to "Leg Raises"),
    "Russian Twists" to ("Rotação Russa" to "Russian Twists"),
    "Deep Breathing" to ("Respiração Profunda" to "Deep Breathing"),
    "Hamstring Stretch" to ("Alongamento de Isquiotibiais" to "Hamstring Stretch"),
    "Shoulder Stretch" to ("Alongamento de Ombros" to "Shoulder Stretch")
)

fun t(key: String, lang: Lang): String {
    val pair = strings[key] ?: return key
    return if (lang == Lang.PT) pair.first else pair.second
}

/** Exposed for tests only: lets us assert full PT/EN coverage of plan-engine content. */
internal fun hasTranslation(key: String): Boolean = strings.containsKey(key)

val LocalLang = compositionLocalOf { Lang.PT }

@Composable
fun ProvideLang(lang: Lang, content: @Composable () -> Unit) {
    CompositionLocalProvider(LocalLang provides lang, content = content)
}
